name: Main flow

on: push

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run unit tests
        run: make unit-test

  int-test:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - uses: engineerd/setup-kind@v0.4.0
      - name: Run int tests
        run: sudo add-apt-repository ppa:duggan/bats && sudo apt-get update && sudo apt-get install bats -y && make int-test

  static:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Run static linters
        run: make static

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Build releases
        run: make releases
        if: startsWith(github.ref, 'refs/tags/')
      - name: Fetch remote references
        run: |
          git fetch --no-tags --prune --depth=1 origin +refs/heads/*:refs/remotes/origin/*
      - name: Generate Changelog
        run: git diff origin/master HEAD --no-ext-diff --unified=0 --exit-code -a --no-prefix CHANGELOG.md | egrep "^\+" | tail -n +2 | sed "s/^+//g" > "${{ github.workflow }}-CHANGELOG.txt"
      - name: Release
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body_path: "${{ github.workflow }}-CHANGELOG.txt"
          files: releases/*.tar.gz
          draft: true
