name: Integration test in Windows

on: push

jobs:
  int-test:
    runs-on: windows-latest
    steps:
      - name: Set up Go 1.14
        uses: actions/setup-go@v1
        with:
          go-version: 1.14
        id: go
      - name: Checkout
        uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Clone bats repository
        run: git clone https://github.com/bats-core/bats-core.git
      - name: Execute bats
        run: bash bats-core/bin/bats tests/managers.test
